### PR TITLE
Fix display showcases

### PR DESCRIPTION
**Pull request by stefina**

### CODE REVIEW

**Comment by stefina** [comment]
Can you have a look at this PR as well, if you have time @amercader ? 
This fix is somewhat associated to https://github.com/ckan/ckanext-showcase/issues/41 
The way I fixed it, is that when permissions to a (associated) dataset or (associated) showcase aren't met, it is removed from the result instead of causing an error. I added a test and hope that this makes it more understandable why this fix is needed.

**Comment by metaodi** [comment]
@stefina please add a test to check your changes in `package_showcase_list`, I'd propose a test that creates a dataset and two showcases, then set one showcase to private, which should trigger the `NotAuthorized` error you're catching.

**Comment by amercader** [comment]
@metaodi @stefina this looks great. You should now have permissions on this repo. Feel free to merge once the tests pass and you are happy with it (and more generally any other PR)

**Comment by metaodi** [comment]
@amercader neither me nor @stefina have permissions to merge on this repo. Maybe you can quickly check?

**Comment by amercader** [comment]
sorry, can you try now?

**Comment by metaodi** [comment]
@amercader it works now, thanks!

**Pull request merged**
